# Generated by Django 4.2.3 on 2023-07-19 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
